handle exit codes in cryptformat and cryptmount

diff --git a/src/cryptformat b/src/cryptformat
--- a/src/cryptformat
+++ b/src/cryptformat
@@ -69,5 +69,10 @@ unset KEY
 /sbin/mkfs.xfs -f "${CRYPT_DEVICE}" \
 	&& /sbin/cryptsetup luksClose "$(basename "${CRYPT_DEVICE}")"
 
-echo "Device '${DEVICE}' was successfully formatted."
-exit 0
+RET=$?
+if [[ "${RET}" -eq 0 ]]; then
+	echo "Device '${DEVICE}' was successfully formatted."
+else
+	echo "Could not format device ${DEVICE}"
+fi
+exit ${RET}
diff --git a/src/cryptmount b/src/cryptmount
--- a/src/cryptmount
+++ b/src/cryptmount
@@ -64,5 +64,10 @@ MOUNTDIR=/mnt/$(uuidgen --md5 --namespace @url --name "${DEVPATH}")
 mkdir -p "${MOUNTDIR}" && mount "${CRYPT_DEVICE}" "${MOUNTDIR}" &>/dev/null \
 	&& /bin/systemctl daemon-reload
 
-echo "Device ${DEVICE} was successfully mounted on ${MOUNTDIR}"
-exit 0
+RET=$?
+if [[ "${RET}" -eq 0 ]]; then
+	echo "Device ${DEVICE} was successfully mounted on ${MOUNTDIR}"
+else
+	echo "Could not mount device ${DEVICE} on ${MOUNTDIR}"
+fi
+exit ${RET}
