improve error handling and error messages

diff --git a/src/crypteject b/src/crypteject
--- a/src/crypteject
+++ b/src/crypteject
@@ -38,14 +38,29 @@ if [[ -z "${DEVPATH}" ]]; then
 fi
 MOUNTDIR=/mnt/$(uuidgen --md5 --namespace @url --name "${DEVPATH}")
 
-umount "${CRYPT_DEVICE}" &>/dev/null && /sbin/cryptsetup luksClose "$(basename "${CRYPT_DEVICE}")" \
-	&& (touch "/mnt/.crypteject" && rmdir -p "${MOUNTDIR}" &>/dev/null || true && rm "/mnt/.crypteject") \
-	&& sync && hdparm -Y "${DEVICE}" &>/dev/null || true && /bin/systemctl daemon-reload
-
-RET=$?
-if [[ "${RET}" -eq 0 ]]; then
-	echo "Device ${DEVICE} can now be safely removed."
-else
-	echo "Could not fully eject device ${DEVICE}"
+if [[ ! -e "${CRYPT_DEVICE}" ]]; then
+	echo "Cannot unmount LUKS device ${CRYPT_DEVICE}; path does not exist."
+	exit 1
 fi
-exit ${RET}
+
+if ! umount "${CRYPT_DEVICE}" &>/dev/null; then
+	echo "Could not unmount filesystem from ${CRYPT_DEVICE}"
+	exit 1
+fi
+
+if ! /sbin/cryptsetup luksClose "$(basename "${CRYPT_DEVICE}")" &>/dev/null; then
+	echo "Could not close LUKS device ${CRYPT_DEVICE}"
+	exit 1
+fi
+
+if ! { touch "/mnt/.crypteject" && rmdir -p "${MOUNTDIR}" &>/dev/null || true && rm "/mnt/.crypteject"; }; then
+	echo "Could not remove mount directory ${MOUNTDIR}"
+	exit 1
+fi
+
+if ! { sync && hdparm -Y "${DEVICE}" &>/dev/null; }; then
+	echo "WARNING: device ${DEVICE} could not be synced or powered down."
+else
+	echo "Device ${DEVICE} can now be safely removed."
+fi
+exit 0
diff --git a/src/cryptformat b/src/cryptformat
--- a/src/cryptformat
+++ b/src/cryptformat
@@ -54,7 +54,11 @@ KEY=$(argon2 "${SEED}" -id -r -t 16 -m 16 -p 16 <"${KEYFILE}")
 
 export KEY
 
-/sbin/cryptsetup -q --type luks2 luksFormat "${DEVICE}" <(printenv KEY | xxd -p -r)
+if ! /sbin/cryptsetup -q --type luks2 luksFormat "${DEVICE}" <(printenv KEY | xxd -p -r); then
+	echo "Could not LUKS format device ${DEVICE}"
+	exit 1
+fi
+
 ID_FS_UUID=$(blkid -s UUID -o value "${DEVICE}")
 CRYPT_DEVICE="/dev/mapper/crypt-${ID_FS_UUID}"
 
@@ -66,13 +70,15 @@ fi
 
 unset KEY
 
-/sbin/mkfs.xfs -f "${CRYPT_DEVICE}" \
-	&& /sbin/cryptsetup luksClose "$(basename "${CRYPT_DEVICE}")"
-
-RET=$?
-if [[ "${RET}" -eq 0 ]]; then
-	echo "Device '${DEVICE}' was successfully formatted."
-else
-	echo "Could not format device ${DEVICE}"
+if ! /sbin/mkfs.xfs -f "${CRYPT_DEVICE}"; then
+	echo "Could not create filesystem on device ${DEVICE}"
+	exit 1
 fi
-exit ${RET}
+
+if ! /sbin/cryptsetup luksClose "$(basename "${CRYPT_DEVICE}")"; then
+	echo "Could not close LUKS device ${CRYPT_DEVICE}"
+	exit 1
+fi
+
+echo "Device '${DEVICE}' was successfully formatted."
+exit 0
diff --git a/src/cryptmount b/src/cryptmount
--- a/src/cryptmount
+++ b/src/cryptmount
@@ -51,7 +51,14 @@ KEY=$(argon2 "${SEED}" -id -r -t 16 -m 16 -p 16 <"${KEYFILE}")
 
 export KEY
 
-/sbin/cryptsetup luksOpen --key-file <(printenv KEY | xxd -p -r) "${DEVICE}" "$(basename "${CRYPT_DEVICE}")"
+if ! /sbin/cryptsetup luksOpen --key-file <(printenv KEY | xxd -p -r) "${DEVICE}" "$(basename "${CRYPT_DEVICE}")" &>/dev/null; then
+	if [[ -e "${CRYPT_DEVICE}" ]]; then
+		echo "Cannot create LUKS device ${CRYPT_DEVICE}; path already exists."
+	else
+		echo "Could not open LUKS device ${DEVICE} using keyfile ${KEYFILE}"
+	fi
+	exit 1
+fi
 
 unset KEY
 
@@ -61,13 +68,10 @@ if [[ -z "${DEVPATH}" ]]; then
 fi
 MOUNTDIR=/mnt/$(uuidgen --md5 --namespace @url --name "${DEVPATH}")
 
-mkdir -p "${MOUNTDIR}" && mount "${CRYPT_DEVICE}" "${MOUNTDIR}" &>/dev/null \
-	&& /bin/systemctl daemon-reload
-
-RET=$?
-if [[ "${RET}" -eq 0 ]]; then
-	echo "Device ${DEVICE} was successfully mounted on ${MOUNTDIR}"
-else
+if ! { mkdir -p "${MOUNTDIR}" && mount "${CRYPT_DEVICE}" "${MOUNTDIR}" &>/dev/null; }; then
 	echo "Could not mount device ${DEVICE} on ${MOUNTDIR}"
+	exit 1
 fi
-exit ${RET}
+
+echo "Device ${DEVICE} was successfully mounted on ${MOUNTDIR}"
+exit 0
